"""知识图谱种子数据——预定义的数据结构知识点树

⚠️ 已废弃：此文件的数据不再用于数据库初始化。
   实际的种子数据位于 app/db/session.py（《数据结构》8 章体系，45 个节点）。
   此文件保留仅作为历史参考，请勿使用 get_all_knowledge_nodes()。
"""
from app.models.knowledge_graph import KnowledgeNode

KNOWLEDGE_NODES = [
    # ═══ 第1大类：线性结构 ═══
    {
        "id": "linear",
        "title": "线性结构",
        "description": "数据结构的基础——线性表及其变体",
        "full_desc": "线性结构是最基本的数据结构，包括数组、链表、栈和队列等，是所有高级数据结构的基石。",
        "category": "linear",
        "difficulty": 1,
        "order_index": 100,
        "parent_id": None,  # 顶级分类节点
        "prerequisites": None,
        "icon": "📏",
        "points": ["数组", "链表", "栈", "队列"],
        "ai_suggestion": "这是数据结构之旅的起点，建议从数组开始，逐步过渡到链表，再学习栈和队列。",
    },
    {
        "id": "array",
        "title": "数组",
        "description": "连续内存中的元素序列",
        "full_desc": "数组是最基础的数据结构，在连续内存空间中存储相同类型的元素，支持 O(1) 随机访问。",
        "category": "linear",
        "difficulty": 1,
        "order_index": 101,
        "parent_id": "linear",
        "prerequisites": None,
        "icon": "🔢",
        "points": ["静态数组", "动态数组", "多维数组", "内存分配与寻址"],
        "ai_suggestion": "数组是最简单也最重要的数据结构。建议先掌握基本操作，再理解内存模型。",
    },
    {
        "id": "linked_list",
        "title": "链表",
        "description": "链式存储的线性表",
        "full_desc": "链表通过指针连接节点，支持 O(1) 插入删除，但需要 O(n) 查找。",
        "category": "linear",
        "difficulty": 2,
        "order_index": 102,
        "parent_id": "linear",
        "prerequisites": ["array"],
        "icon": "🔗",
        "points": ["单链表", "双向链表", "循环链表", "链表反转", "合并链表", "快慢指针"],
        "ai_suggestion": "链表是面试高频考点。重点掌握指针操作和常见变体（反转、合并、找环）。",
    },
    {
        "id": "stack",
        "title": "栈",
        "description": "后进先出（LIFO）的受限线性表",
        "full_desc": "栈是只允许在一端进行插入和删除的线性表，遵循后进先出原则。",
        "category": "linear",
        "difficulty": 2,
        "order_index": 103,
        "parent_id": "linear",
        "prerequisites": ["array"],
        "icon": "📚",
        "points": ["顺序栈", "链式栈", "括号匹配", "表达式求值", "函数调用栈", "单调栈"],
        "ai_suggestion": "栈的核心是 LIFO 原则。重点练习括号匹配、表达式求值和单调栈技巧。",
    },
    {
        "id": "queue",
        "title": "队列",
        "description": "先进先出（FIFO）的受限线性表",
        "full_desc": "队列是只允许在一端插入、另一端删除的线性表，遵循先进先出原则。",
        "category": "linear",
        "difficulty": 2,
        "order_index": 104,
        "parent_id": "linear",
        "prerequisites": ["array", "linked_list"],
        "icon": "🚶",
        "points": ["顺序队列", "链式队列", "循环队列", "双端队列", "优先队列"],
        "ai_suggestion": "理解队列的 FIFO 特性。循环队列可以解决'假溢出'问题，优先队列是算法竞赛常客。",
    },

    # ═══ 第2大类：树形结构 ═══
    {
        "id": "tree",
        "title": "树形结构",
        "description": "层次化的非线性数据结构",
        "full_desc": "树是 n 个节点的有限集合，有一个根节点，其余节点分为互不相交的子树。",
        "category": "tree",
        "difficulty": 3,
        "order_index": 200,
        "parent_id": None,
        "prerequisites": ["linked_list"],
        "icon": "🌳",
        "points": ["树的基本概念", "二叉树", "二叉搜索树", "平衡树"],
        "ai_suggestion": "树是非线性结构的开端，是面试中最重要的数据结构之一。建议先掌握遍历方式。",
    },
    {
        "id": "binary_tree",
        "title": "二叉树",
        "description": "每个节点最多两个子节点的树",
        "full_desc": "二叉树是最基本的树形结构，每个节点最多有两个子节点：左子节点和右子节点。",
        "category": "tree",
        "difficulty": 3,
        "order_index": 201,
        "parent_id": "tree",
        "prerequisites": ["linked_list", "stack"],
        "icon": "🌿",
        "points": ["前序遍历", "中序遍历", "后序遍历", "层序遍历", "递归/迭代实现", "Morris遍历"],
        "ai_suggestion": "三种遍历是二叉树的核心。递归版本简单，迭代版本需要借助栈，面试常考。",
    },
    {
        "id": "bst",
        "title": "二叉搜索树",
        "description": "左 < 根 < 右 的有序二叉树",
        "full_desc": "BST 的每个节点左子树值小于根，右子树值大于根，支持 O(log n) 的查找/插入/删除。",
        "category": "tree",
        "difficulty": 3,
        "order_index": 202,
        "parent_id": "tree",
        "prerequisites": ["binary_tree"],
        "icon": "🔍",
        "points": ["BST 性质", "插入/删除/查找", "验证 BST", "BST 的局限（退化）"],
        "ai_suggestion": "BST 是理解平衡树的基础。注意最坏情况会退化成链表，引出了平衡树的需求。",
    },
    {
        "id": "avl_rbtree",
        "title": "平衡二叉树",
        "description": "AVL 树与红黑树",
        "full_desc": "平衡树通过旋转操作保持树的高度平衡，确保 O(log n) 的操作复杂度。",
        "category": "tree",
        "difficulty": 4,
        "order_index": 203,
        "parent_id": "tree",
        "prerequisites": ["bst"],
        "icon": "⚖️",
        "points": ["AVL 树旋转", "红黑树性质", "插入调整", "删除调整", "应用场景"],
        "ai_suggestion": "红黑树是 C++ map/set 的底层实现。理解旋转和着色规则，不必死记所有情况。",
    },
    {
        "id": "heap",
        "title": "堆",
        "description": "优先队列的底层实现",
        "full_desc": "堆是一种特殊的完全二叉树，满足堆序性质（大顶堆/小顶堆）。",
        "category": "tree",
        "difficulty": 3,
        "order_index": 204,
        "parent_id": "tree",
        "prerequisites": ["binary_tree", "array"],
        "icon": "⛰️",
        "points": ["大顶堆/小顶堆", "堆的构建", "堆排序", "TopK 问题", "优先队列"],
        "ai_suggestion": "堆排序和 TopK 是面试高频题。用数组存储完全二叉树是重要的工程技巧。",
    },

    # ═══ 第3大类：图 ═══
    {
        "id": "graph",
        "title": "图",
        "description": "节点和边的非线性结构",
        "full_desc": "图由顶点集合和边集合组成，可以表示复杂的关系网络。",
        "category": "graph",
        "difficulty": 4,
        "order_index": 300,
        "parent_id": None,
        "prerequisites": ["tree", "queue"],
        "icon": "🕸️",
        "points": ["图的表示", "BFS/DFS", "最短路径", "最小生成树", "拓扑排序"],
        "ai_suggestion": "图是最灵活的数据结构。建议先掌握邻接表/邻接矩阵，然后学习 BFS 和 DFS。",
    },
    {
        "id": "graph_traversal",
        "title": "图的遍历",
        "description": "BFS 与 DFS 在图中的应用",
        "full_desc": "BFS 用队列实现逐层遍历，DFS 用栈/递归深入探索，是图算法的基础。",
        "category": "graph",
        "difficulty": 4,
        "order_index": 301,
        "parent_id": "graph",
        "prerequisites": ["stack", "queue", "binary_tree"],
        "icon": "🚶‍♂️",
        "points": ["邻接表/邻接矩阵", "BFS", "DFS", "连通分量", "二分图判定"],
        "ai_suggestion": "图的遍历是图算法的基石。理解 BFS 求最短路径、DFS 求连通分量。",
    },
    {
        "id": "shortest_path",
        "title": "最短路径",
        "description": "Dijkstra 与其他最短路径算法",
        "full_desc": "从起点到终点的最短路径计算，根据不同场景使用不同算法。",
        "category": "graph",
        "difficulty": 4,
        "order_index": 302,
        "parent_id": "graph",
        "prerequisites": ["graph_traversal", "heap"],
        "icon": "🗺️",
        "points": ["Dijkstra", "Bellman-Ford", "Floyd-Warshall", "A* 搜索"],
        "ai_suggestion": "Dijkstra 是最常用的最短路径算法。理解贪心策略和优先队列优化的原理。",
    },
    {
        "id": "mst",
        "title": "最小生成树",
        "description": "连接所有节点的最小代价",
        "full_desc": "在连通带权无向图中找出一棵权值和最小的生成树。",
        "category": "graph",
        "difficulty": 4,
        "order_index": 303,
        "parent_id": "graph",
        "prerequisites": ["graph_traversal"],
        "icon": "🌐",
        "points": ["Kruskal 算法", "Prim 算法", "并查集", "网络设计应用"],
        "ai_suggestion": "Kruskal + 并查集是经典组合。Prim 算法与 Dijkstra 思想类似，可以对比学习。",
    },

    # ═══ 第4大类：散列 ═══
    {
        "id": "hashing",
        "title": "散列与查找",
        "description": "O(1) 时间复杂度的存储与查找",
        "full_desc": "散列技术通过哈希函数将键映射到存储位置，实现近乎 O(1) 的查找。",
        "category": "hashing",
        "difficulty": 3,
        "order_index": 400,
        "parent_id": None,
        "prerequisites": ["array", "linked_list"],
        "icon": "🔑",
        "points": ["哈希表", "哈希函数", "冲突解决", "布隆过滤器", "二分查找"],
        "ai_suggestion": "哈希表是使用最广泛的数据结构。理解哈希函数设计和冲突解决策略。",
    },
    {
        "id": "hash_table",
        "title": "哈希表",
        "description": "键值对的快速存储结构",
        "full_desc": "通过哈希函数将任意大小的 key 映射为固定大小的索引，实现快速存取。",
        "category": "hashing",
        "difficulty": 3,
        "order_index": 401,
        "parent_id": "hashing",
        "prerequisites": ["array"],
        "icon": "🗄️",
        "points": ["哈希函数设计", "链地址法", "开放寻址法", "装载因子", "再哈希"],
        "ai_suggestion": "掌握链地址法和开放寻址法两种冲突解决策略。面试常考哈希表实现 LRU 缓存。",
    },
    {
        "id": "binary_search",
        "title": "二分查找",
        "description": "在有序序列中的高效查找",
        "full_desc": "每次将查找范围缩小一半，O(log n) 时间复杂度。",
        "category": "hashing",
        "difficulty": 2,
        "order_index": 402,
        "parent_id": "hashing",
        "prerequisites": ["array"],
        "icon": "🎯",
        "points": ["标准二分", "左边界/右边界", "旋转数组查找", "二分答案"],
        "ai_suggestion": "二分查找思想简单但细节容易出错。注意边界条件和 mid 计算，练习多种变体。",
    },

    # ═══ 第5大类：排序 ═══
    {
        "id": "sorting",
        "title": "排序算法",
        "description": "将元素按序排列的各种策略",
        "full_desc": "排序是将无序序列变为有序序列的过程，不同算法有不同时间/空间复杂度。",
        "category": "sorting",
        "difficulty": 3,
        "order_index": 500,
        "parent_id": None,
        "prerequisites": ["array"],
        "icon": "📊",
        "points": ["比较排序", "非比较排序", "排序的稳定性", "时间复杂度分析"],
        "ai_suggestion": "排序是算法入门必修课。建议先掌握基础排序，再学习快排和归并排序。",
    },
    {
        "id": "basic_sort",
        "title": "基础排序",
        "description": "冒泡、选择、插入排序",
        "full_desc": "三种最基础的排序算法，时间复杂度 O(n²)，但插入排序在小规模数据上表现良好。",
        "category": "sorting",
        "difficulty": 2,
        "order_index": 501,
        "parent_id": "sorting",
        "prerequisites": ["array"],
        "icon": "🫧",
        "points": ["冒泡排序", "选择排序", "插入排序", "稳定性的理解"],
        "ai_suggestion": "从这三种基础排序入手，理解排序算法的基本思想和稳定性概念。",
    },
    {
        "id": "advanced_sort",
        "title": "高级排序",
        "description": "快排、归并排序、堆排序",
        "full_desc": "时间复杂度 O(n log n) 的高效排序算法，各有优劣。",
        "category": "sorting",
        "difficulty": 3,
        "order_index": 502,
        "parent_id": "sorting",
        "prerequisites": ["basic_sort", "binary_tree"],
        "icon": "⚡",
        "points": ["快速排序", "归并排序", "堆排序", "分治思想", "排序选择指南"],
        "ai_suggestion": "快排是实际应用最广泛的排序算法。归并排序的合并思想在很多问题中都有应用。",
    },

    # ═══ 第6大类：算法思维 ═══
    {
        "id": "algorithms",
        "title": "算法思想",
        "description": "通用的问题求解策略",
        "full_desc": "掌握核心算法设计范式，将具体问题抽象为通用模型。",
        "category": "algorithms",
        "difficulty": 5,
        "order_index": 600,
        "parent_id": None,
        "prerequisites": ["tree", "graph", "sorting"],
        "icon": "🧠",
        "points": ["动态规划", "贪心算法", "回溯法", "分治法", "双指针/滑动窗口"],
        "ai_suggestion": "这是数据结构和算法学习的集大成阶段。需要综合运用前面所有知识。",
    },
    {
        "id": "dp",
        "title": "动态规划",
        "description": "最优子结构与重叠子问题",
        "full_desc": "动态规划通过将问题分解为子问题并保存子问题解来高效求解，是最重要的算法设计范式之一。",
        "category": "algorithms",
        "difficulty": 5,
        "order_index": 601,
        "parent_id": "algorithms",
        "prerequisites": ["array", "recursion"],
        "icon": "📈",
        "points": ["DP 五步法", "背包问题", "LIS/LCS", "区间DP", "树形DP", "状态压缩"],
        "ai_suggestion": "DP 是算法中最难也最重要的部分。建议从简单的斐波那契开始，逐步过渡到背包和区间DP。",
    },
    {
        "id": "recursion",
        "title": "递归与分治",
        "description": "将大问题分解为小问题求解",
        "full_desc": "递归是函数调用自身的编程技巧，分治是将问题分解为独立子问题求解的策略。",
        "category": "algorithms",
        "difficulty": 3,
        "order_index": 602,
        "parent_id": "algorithms",
        "prerequisites": ["stack"],
        "icon": "🔄",
        "points": ["递归三要素", "分治策略", "归并排序的分治应用", "递归与栈的关系"],
        "ai_suggestion": "理解递归需要先理解函数调用栈。多画递归树有助于理解递归过程。",
    },
    {
        "id": "greedy",
        "title": "贪心算法",
        "description": "每一步做出当前最优选择",
        "full_desc": "贪心算法在每一步都选择当前看起来最优的方案，期望最终得到全局最优解。",
        "category": "algorithms",
        "difficulty": 4,
        "order_index": 603,
        "parent_id": "algorithms",
        "prerequisites": ["sorting"],
        "icon": "🎯",
        "points": ["贪心正确性证明", "区间调度", "哈夫曼编码", "Prim 算法贪心应用"],
        "ai_suggestion": "贪心的关键是证明正确性。可以先假设贪心策略是正确的，再尝试验证或找反例。",
    },
]


def get_all_knowledge_nodes() -> list[KnowledgeNode]:
    """⚠️ 已废弃：请使用 app/db/session.py 中的章节体系种子数据"""
    import warnings
    warnings.warn("seed.get_all_knowledge_nodes() is deprecated. Use data from app/db/session.py instead.", DeprecationWarning, stacklevel=2)
    return [KnowledgeNode(**data) for data in KNOWLEDGE_NODES]
